---
version: "3"
services:
  sheriffs-bot:
    build: .
    container_name: discord-sheriffs-bot
    volumes:
      - "./data/:/app/data:rw"
    environment:
      - UID=1000 
      - GID=1000
      - TOKEN=
      - PREFIX=s!
      - OWNER_ID=
      - OWNER_NAME=Chris#1234
      - REQUIRED_MESSAGES=40
      - VERSION=v1.0.1
    stdin_open: true
    tty: true
    restart: unless-stopped